### ISSUE TITLE
CLI Mode seems to enable Ping over Population by default. But there is no argument to force enable Population over ping :( 

### ISSUE THREAD

**Issue by vibinator** [EchoTools/EchoRelay#10]

**Comment by thesprockee** [comment]
Does this need a `--populationmatching` argument added? or should population be the default when `--lowpingmatching` isn't provided?

https://github.com/EchoTools/EchoRelay/blob/55a4e43c4c1df679d8cf94ba6f47f6cf3f7f5023/EchoRelay.Cli/Program.cs#L57C17-L57C17

**Comment by vibinator** [comment]
Yes, We need a --populationmatching added. 

 We've had some people report that keep getting into 1v0 nonstop. However there are higher population games ongoing..
