### ISSUE TITLE
Need to ability to ban people using CLI 

### ISSUE THREAD

**Issue by vibinator** [EchoTools/EchoRelay#11]
Need to ability to ban people using CLI  and/or via Account Config (It seems to overwrite upon the user logging on/off

**Comment by thesprockee** [comment]
IMHO The file cache (LRUFileCache) should check the file mtime as part of it's cache lookup too.

**Comment by thesprockee** [comment]
Fixed in a9f4d5d195877322d8b08985a7c8867aafb141e5
