### ISSUE TITLE
Turn off the Server Log section in the GUI to increase performance/error handling 

### ISSUE THREAD

**Issue by vibinator** [EchoTools/EchoRelay#12]
Turn off the Server Log section in the GUI to increase performance/error handling

**Comment by thesprockee** [comment]
Is this an I/O issues, or some settings? How many log entries per second cause the performance issue?

**Comment by vibinator** [comment]
> Is this an I/O issues, or some settings? How many log entries per second cause the performance issue?

Hey, All i know is that the GUI Version is far less stable than the CLI, this is mainly caused by the extra logs or stats updating. As it occurs during the transition from a game to a lobby
