### ISSUE TITLE
Bans are not sticking when using CLI

### ISSUE THREAD

**Issue by vibinator** [EchoTools/EchoRelay#17]
IT looks like the users JSON file on the client side is overwriting it, this shouldn't be editable on the client side, only the server side.

**Comment by vibinator** [comment]
Note: This is when adding the ban section manually in the json, as the CLI doesn't have the ability to do bans

**Comment by thesprockee** [comment]
Yeah. the JSON files use a cache. 

I've added a `--disable-cache` argument that make any changes you do to the files immediately active.

Fixed in a9f4d5d195877322d8b08985a7c8867aafb141e5
